name: "Garrett's Portfolio"
favicon: null
layout_spectrum: 0.02524
typography_spectrum: 0.62075
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191514'
    - '#c8ccd7'
    - '#907d76'
    - '#6c5b4e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
