name: "Garrett's Portfolio"
favicon: null
layout_spectrum: 0.88879
typography_spectrum: 0.61354
title: "Garrett Sherwood'd Portfolio"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2abaa'
    - '#ededed'
    - '#5e2f1b'
    - '#c4cbd3'
    - '#8e7b6d'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
