name: "Garrett's Portfolio"
favicon: null
layout_spectrum: 0.14427
typography_spectrum: 0.62075
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2abaa'
    - '#ededed'
    - '#5e2f1b'
    - '#c4cbd3'
    - '#8e7b6d'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
