name: "Garrett's Portfolio"
favicon: null
layout_spectrum: 0.02524
typography_spectrum: 0.62075
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#494438'
    - '#011e01'
    - '#ffffff'
    - '#d4d3d0'
    - '#9e9b94'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
